# Recipe format compatibility check i.e. what versions of the assembler does this recipe work with? 
recipe_vsn = "1.0.0"



# About the solution as a whole
[solution]
    name = "Agri"
    slug = "agri"
    version = "1.0.0"
    description = "Agri Demo Lorawan"

# Service module instances present in this solution
[service_module.lorawan]
    source="lorawan"
    containers = ["lora"]
    template.log_level = "debug"

[service_module.data-storage]
    source = "data_storage"
    containers = ["influx","telegraf"]
    ports.influx.ui = 8086
    alias.influx = "timeseries-db"

[service_module.dashboards]
    source = "grafana"
    containers = ["grafana"]
    ports.grafana.ui = 3000
    template.disable_sanitise_html = "true"

[service_module.analysis]
    source = "analysis"
    containers = ["analysis-sm"]
    ports.analysis-sm.api = 8000
    alias.analysis-sm = "analysis"
    template.log_level = "info"

[service_module.graph]
    source = "graph_src"
    containers = ["graph-sm"]
    alias.graph-sm = "graph"
    ports.graph-sm.ui = 8080


# Infrastructure modules present in this solution
[infrastructure.mqtt-broker]
    source = "mqtt_broker"
    containers = ["broker"]
    ports.broker.tcp = 1883
    ports.broker.websocket = 9001
    alias.broker = "mqtt"

[infrastructure.logging]
    source = "logging"
    containers = ["alloy","loki"]
    ports.loki.api = 3100
    alias.loki = "loki"
    alias.alloy = "alloy"
    volume.alloy.docker_sock = "/var/run/docker.sock"




# Available module code sources which can feed the above instances
[source.lorawan]
    git.path = "sm_lorawan"
    git.branch = "main"

[source.data_storage]
    git.path = "sm_timeseries_db"
    git.tag = "v2.0.0"

[source.grafana]
    git.path = "sm_grafana_ui"
    git.tag = "v2.2.0"

[source.mqtt_broker]
    git.path = "sm_mqtt_broker"
    git.tag = "v2.0.0"

[source.logging]
    git.path = "Logging"
    git.tag = "v1.0.1"


[source.analysis]
    git.path = "sm_analysis"
    git.tag = "v0.2.3"

[source.graph_src]
    file.path = "./custom_service_modules/graph"
    file.mode = "link"
