[mapper]
    topic_pattern = "{gw}/{DeviceID}/{type}"    # only the DeviceID field matters, the rest are wildcard placeholders


[mapping.0185196C]
    type = "llms01"
    identifier = "Water A"
    output_topic = "flow/{identifier}"


[mqtt_in]
    broker = "mqtt.docker.local"
    port = 1883   #common mqtt ports are 1883 and 8883
    topic_prefix = ""

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds

[mqtt_out]
    broker = "mqtt.docker.local"
    port = 1883   #common mqtt ports are 1883 and 8883
    topic_prefix = ""

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds